# Header
menu:
  Home: /blog
  Archives: /blog/archives
rss: #/blog/atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /blog/favicon.png
twitter:
google_plus:
